name: Gitleaks

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Gitleaks
        run: |
          docker run --rm -v $(pwd):/code zricethezav/gitleaks
